# Generated by Django 3.1.2 on 2021-04-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210413_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='Frist_name',
            new_name='First_name',
        ),
    ]
